// Aggregates every command family so the dispatcher imports one module.

module.exports = {
  ...require('./email-events'),
  ...require('./auth'),
  ...require('./maintenance'),
  ...require('./crm'),
  ...require('./project'),
  ...require('./agent-cli'),
  ...require('./properties'),
  ...require('./associations'),
  ...require('./users'),
  ...require('./owners'),
  ...require('./account'),
  ...require('./tiers'),
  ...require('./commerce'),
  ...require('./schemas'),
  ...require('./pipelines'),
  ...require('./lists'),
  ...require('./imports-exports'),
  ...require('./subscriptions'),
  ...require('./files'),
  ...require('./events'),
  ...require('./webhooks'),
  ...require('./conversations'),
  ...require('./marketing'),
  ...require('./automation'),
  ...require('./extensions'),
  ...require('./forms'),
  ...require('./cms'),
  ...require('./scheduler'),
  ...require('./limits'),
};
